name: Build

on:
  push:
    tags: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container: quay.io/pypa/manylinux1_x86_64

    env:
      PATH: /opt/python/cp38-cp38/bin:/opt/python/cp37-cp37m/bin:/opt/rh/devtoolset-8/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry export --dev --format requirements.txt > dev-requirements.txt
        pip install --requirement dev-requirements.txt
    - name: Build distributions
      run: |
        ./scripts/build.sh
    - uses: actions/upload-artifact@v1
      with:
        name: python-packages
        path: dist
    - uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: bin

