name: Linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry export --dev --format requirements.txt > dev-requirements.txt
        pip install --requirement dev-requirements.txt
    - name: Lint with isort
      run: isort --check-only --recursive src
    - name: Lint with black
      run: black --check src
    - name: Lint with flake8
      run: flake8 src
